version = 3.10.7
runner.dialect = scala3
maxColumn = 100
lineEndings = unix
rewrite.rules = [RedundantBraces, SortImports]
rewrite.scala3.convertToNewSyntax = true
docstrings.style = Asterisk
docstrings.wrap = yes
newlines.source = fold
newlines.beforeMultiline = unfold
spaces.inImportCurlyBraces = true
project.git = true

